### ISSUE TITLE
exists() string is incorrect

### ISSUE THREAD

**Issue by mikelentini** [pnann/check-preconditions#1]
All of the check strings specify what the result _should_ be, such as `"true"`, `"false"`, `"empty"`. So when the check fails you get `"was not true"`, `"was not false"`, `"was not empty"`. The `exists()` string is actually specifying what the result _should not_ be, i.e. `"null or undefined"`. This is why when the `exists()` check fails it prints out `"was not null or undefined"` when it actually means that it _was_ `null` or `undefined`. Not sure off the top of my head what the correct string should be or if a code change is necessary.

**Comment by pnann** [comment]
Thanks for the report, Mike!

Fixed in https://github.com/pnann/check-preconditions/commit/fd19c796faa43424fb10ade27c7ad5dabff71c6d and released as version [0.2.1](https://github.com/pnann/check-preconditions/releases/tag/0.2.1)
