### ISSUE TITLE
Update for @types

### ISSUE THREAD

**Issue by koceskik** [pnann/check-preconditions#2]
Please add:
"types": "check-preconditions.d.ts"
or
"typings": "check-preconditions.d.ts"

to the package.json, or publish a separate @types, to publish the declaration file (https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html).

**Comment by pnann** [comment]
Thanks for reporting this! Added as part of [`1.0.0-rc.1`](https://github.com/pnann/check-preconditions/commit/9a9375f3dc73127946842d9fb639bcf63be24acd).
