### ISSUE TITLE
Ability to check numbers

### ISSUE THREAD

**Issue by Shinigami92** [pnann/check-preconditions#26]
Is there a way to check if a `target` is greater, less or equals to a specified number?

I have the current structure:
```ts
// value := [string, string, string?]
check(value, 'value').exists();
check(value, 'value').is.an.array();

check<number>(value.length, 'value').is.ge(2); // Greater or equals 2
check<number>(value.length, 'value').is.le(3); // Less or equals 3

check<number>(value.length, 'value').is.between(2, 3); // Between 2 and 3

check<number>(value.length, 'value').is.gt(1); // Greater 1
check<number>(value.length, 'value').is.lt(4); // Less 1

// ...
```

I want to check in this way so that I don't break the code flow and use this "style of check" as a preconditions.

**Comment by pnann** [comment]
Looks reasonable to me. Thanks for the feature request!

**Comment by pnann** [comment]
Just pushed the change to add `between` and `within`. This will go out in version 1.1.0, which shouldn't be too far down the road -- let me know if anything else comes to mind, @Shinigami92!
